services:
  # oline-phone-shop:
  #   build: .
  #   container_name: oline-phone-shop
  #   ports:
  #     - '5050:5050'
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis
  #   networks:
  #     - super-net
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: npm run start:dev

  # super-db-nestjs:
  #   image: postgres
  #   container_name: nest-js-super-db
  #   environment:
  #     POSTGRES_USER: ${PG_USER}
  #     POSTGRES_PASSWORD: ${PG_PASSWORD}
  #     POSTGRES_HOST: ${PG_HOST}
  #     POSTGRES_PORT: ${PG_PORT}
  #     POSTGRES_DATABASE: ${PG_DATABASE}
  #   ports:
  #     - '5433:5432'
  #   networks:
  #     - super-net
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6383:6379'
    networks:
      - oline-phone-shop_super-net-app

volumes:
  postgres_data:


networks:
  oline-phone-shop_super-net-app:
    driver: bridge
